name: GraspWithObject

guidance_scale: 1
grad_scale: 0.1 ####need to be tuned

clip_grad_by_value:
  min: -0.1
  max: 0.1
loss_weights:
  SRF_loss: 1.0      
  SPF_loss: 1.0      
  ERF_loss: 0.3 
asset_dir: ${task.dataset.asset_dir}
asset_dir_slurm: ${task.dataset.asset_dir_slurm}

batch_size: ${task.test.batch_size}
modeling_keys: ${task.dataset.modeling_keys}

normalize_x: ${task.dataset.normalize_x}
normalize_x_trans: ${task.dataset.normalize_x_trans}