## config/default.yaml
#####################################
# for example:
# bash scripts/grasp_gen_ur/train_ddm.sh unidex
# bash scripts/grasp_gen_ur/sample.sh /inspurfs/group/mayuexin/zym/diffusion+hand/DGA/outputs/2025-03-18_16-39-55_test [OPT]
# bash scripts/grasp_gen_ur/test.sh  /inspurfs/group/mayuexin/zym/diffusion+hand/DGA/outputs/2025-03-16_19-11-48_test/eval/final/2025-03-16_19-15-31
#####################################


hydra:
  run:
    dir: ${exp_dir}
  output_subdir: null

defaults:
  - _self_
  - diffuser: ddpm
  - model: unet_grasp
  - task: grasp_gen_ur
  - optimizer: null


exp_name: default
output_dir: outputs
exp_dir: ${output_dir}/${now:%Y-%m-%d_%H-%M-%S}_${exp_name}
tb_dir: ${exp_dir}/tb_logs
vis_dir: ${exp_dir}/visual
ckpt_dir: ${exp_dir}/ckpts

slurm: false
gpu: 0

## for saving model
save_model_interval: 1
save_model_seperately: true
save_scene_model: true # save scene model or not, important!!!

# Global LLM switch
llm:
  enabled: false  # Master switch for all LLM features
  
# sampling
use_dpmsolver: False # Whether to use dpmsolver++ for sampling

dataset:
  active: real_dex  ## Available options: DexGraspNet, Unidexgrasp, DexGRAB, real_dex, Grasp_anything
  paths:
    MultiDexShadowHandUR:
      asset_dir: /inspurfs/group/mayuexin/datasets/MultiDex_UR
      asset_dir_slurm: /inspurfs/group/mayuexin/datasets/MultiDex_UR
    DexGraspNet:
      asset_dir: /inspurfs/group/mayuexin/datasets/DexGraspNet
      asset_dir_slurm: /inspurfs/group/mayuexin/datasets/DexGraspNet
    Unidexgrasp:
      asset_dir: /inspurfs/group/mayuexin/datasets/UniDexGrasp/DFCData
      asset_dir_slurm: /inspurfs/group/mayuexin/datasets/UniDexGrasp/DFCData
    DexGRAB:
      asset_dir: /inspurfs/group/mayuexin/datasets/DexGRAB
      asset_dir_slurm: /inspurfs/group/mayuexin/datasets/DexGRAB
    real_dex:
      asset_dir: /inspurfs/group/mayuexin/datasets/Realdex
      asset_dir_slurm: /inspurfs/group/mayuexin/datasets/Realdex
    Grasp_anyting:
      asset_dir: /inspurfs/group/mayuexin/datasets/Grasp_anything
      asset_dir_slurm: /inspurfs/group/mayuexin/datasets/Grasp_anything